/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.view;

import br.com.estoque.model.bean.Fornecedor;
import br.com.estoque.model.dao.FornecedorDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rafael
 */
public final class ViewCadastraFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroFornecedor
     */
    public ViewCadastraFornecedor() {
        initComponents();
        DefaultTableModel modeloForn = (DefaultTableModel) JTFornecedor.getModel();
        JTFornecedor.setRowSorter(new TableRowSorter(modeloForn));
        
        JTFornecedor.getColumnModel().getColumn(0).setPreferredWidth(40);
        JTFornecedor.getColumnModel().getColumn(1).setPreferredWidth(250);
        JTFornecedor.getColumnModel().getColumn(2).setPreferredWidth(130);
        JTFornecedor.getColumnModel().getColumn(3).setPreferredWidth(110);
        JTFornecedor.getColumnModel().getColumn(4).setPreferredWidth(100);
        JTFornecedor.getColumnModel().getColumn(5).setPreferredWidth(105);
        JTFornecedor.getColumnModel().getColumn(6).setPreferredWidth(230);
        JTFornecedor.getColumnModel().getColumn(7).setPreferredWidth(120);
        JTFornecedor.getColumnModel().getColumn(8).setPreferredWidth(120);
        JTFornecedor.getColumnModel().getColumn(9).setPreferredWidth(85);
        JTFornecedor.getColumnModel().getColumn(10).setPreferredWidth(100);
        JTFornecedor.getColumnModel().getColumn(11).setPreferredWidth(30);

        readTableFornecedores();
    }

    public void readTableFornecedores(){
        DefaultTableModel modeloForn = (DefaultTableModel) JTFornecedor.getModel();
        modeloForn.setNumRows(0);
        FornecedorDAO dao = new FornecedorDAO();
        
        for(Fornecedor f : dao.read()){
            modeloForn.addRow(new Object[]{
                f.getIdFornecedor(),
                f.getRazaoSocial(),
                f.getCNPJ(),
                f.getIE(),
                f.getFoneFixo(),
                f.getFoneCelular(),
                f.getEmail(),
                f.getResp(),
                f.getEnd(),
                f.getBairro(),
                f.getCidade(),
                f.getUF()
            });
        }
    }
    
    public void readTableFornForDesc(String busca){
        DefaultTableModel modeloForn = (DefaultTableModel) JTFornecedor.getModel();
        modeloForn.setNumRows(0);
        FornecedorDAO dao = new FornecedorDAO();
        
        for(Fornecedor f : dao.readForDesc(busca)){
            modeloForn.addRow(new Object[]{
                f.getIdFornecedor(),
                f.getRazaoSocial(),
                f.getCNPJ(),
                f.getIE(),
                f.getFoneFixo(),
                f.getFoneCelular(),
                f.getEmail(),
                f.getResp(),
                f.getEnd(),
                f.getBairro(),
                f.getCidade(),
                f.getUF()
            });
        }
    }
    
    public void limpaCamposForm(){
        txtRazaoSocial.setText("");
        txtCNPJ.setText("");
        txtIE.setText("");
        txtRua.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        jcbUF.setSelectedIndex(0);
        txtFoneFixo.setText("");
        txtFoneCelular.setText("");
        txtEmail.setText("");
        txtResponsavel.setText("");
        txtBuscaForn.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIE = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbUF = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtFoneFixo = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFoneCelular = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTFornecedor = new javax.swing.JTable();
        btnCadFornecedor = new javax.swing.JButton();
        btnCanFornecedor = new javax.swing.JButton();
        btnExcluirForn = new javax.swing.JButton();
        btnAlterarForn = new javax.swing.JButton();
        txtBuscaForn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtRazaoSocial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Fornecedores");
        setResizable(false);

        jLabel1.setText("Razão Social:");

        jLabel2.setText("CNPJ:");

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("IE:");

        try {
            txtIE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Rua:");

        jLabel6.setText("Bairro:");

        jLabel7.setText("Cidade:");

        jLabel8.setText("UF:");

        jcbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel9.setText("Fixo:");

        try {
            txtFoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Celular:");

        try {
            txtFoneCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Email:");

        jLabel12.setText("Respinsável:");

        JTFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão Social", "CNPJ", "I.E.", "Telefone Fixo", "Telefone Celular", "Email", "Responsável", "Endereço", "Bairro", "Cidade", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTFornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTFornecedor.setSelectionBackground(new java.awt.Color(255, 102, 102));
        JTFornecedor.getTableHeader().setReorderingAllowed(false);
        JTFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFornecedorFocusLost(evt);
            }
        });
        JTFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTFornecedor);

        btnCadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/íconeCad.fw.png"))); // NOI18N
        btnCadFornecedor.setText("  Salvar");
        btnCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFornecedorActionPerformed(evt);
            }
        });

        btnCanFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/iconeCan.fw.png"))); // NOI18N
        btnCanFornecedor.setText("   Cancelar");
        btnCanFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanFornecedorActionPerformed(evt);
            }
        });

        btnExcluirForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/iconeCan.fw.png"))); // NOI18N
        btnExcluirForn.setText("   Excluir");
        btnExcluirForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFornActionPerformed(evt);
            }
        });

        btnAlterarForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/icones/atu.png"))); // NOI18N
        btnAlterarForn.setText("   Alterar");
        btnAlterarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFornActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirForn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCanFornecedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(txtIE, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtCidade)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel9)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 145, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtBuscaForn, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCanFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirForn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFornecedorActionPerformed
        if((txtRazaoSocial.getText().length() <= 0) || (txtCNPJ.getText().length() <= 0) || (txtFoneFixo.getText().length() <= 0) || (txtFoneCelular.getText().length() <= 0)){
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos obrigatórios");
        }else{
            Fornecedor f = new Fornecedor();
            FornecedorDAO dao = new FornecedorDAO();
            
            f.setRazaoSocial(txtRazaoSocial.getText());
            f.setCNPJ(txtCNPJ.getText());
            f.setIE(txtIE.getText());
            f.setEnd(txtRua.getText());
            f.setBairro(txtBairro.getText());
            f.setCidade(txtCidade.getText());
            f.setUF((String) jcbUF.getSelectedItem());
            f.setFoneFixo(txtFoneFixo.getText());
            f.setFoneCelular(txtFoneCelular.getText());
            f.setEmail(txtEmail.getText());
            f.setResp(txtResponsavel.getText());
            
            dao.create(f);
        }
        
        limpaCamposForm();
        readTableFornecedores();
    }//GEN-LAST:event_btnCadFornecedorActionPerformed

    private void btnCanFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanFornecedorActionPerformed
        limpaCamposForm();
        JTFornecedor.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btnCanFornecedorActionPerformed

    private void btnExcluirFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFornActionPerformed
        if(JTFornecedor.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?", "Confirmação de exclusão!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                Fornecedor f = new Fornecedor();
                FornecedorDAO dao = new FornecedorDAO();
                
                f.setIdFornecedor((int) JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 0));
                dao.delete(f);
           }
        }else{
           JOptionPane.showMessageDialog(null, "Selecione um fornecedor para excluir!");
        }
        
        limpaCamposForm();
        readTableFornecedores();
        
    }//GEN-LAST:event_btnExcluirFornActionPerformed

    private void JTFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFornecedorMouseClicked
        if(JTFornecedor.getSelectedRow() != -1){
            txtRazaoSocial.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 1).toString());
            txtCNPJ.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 2).toString());
            txtIE.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 3).toString());
            txtFoneFixo.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 4).toString());
            txtFoneCelular.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 5).toString());
            txtEmail.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 6).toString());
            txtResponsavel.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 7).toString());
            txtRua.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 8).toString());
            txtBairro.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 9).toString());
            txtCidade.setText(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 10).toString());
            jcbUF.setSelectedItem(JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 11).toString());
        }
        
    }//GEN-LAST:event_JTFornecedorMouseClicked

    private void btnAlterarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFornActionPerformed
        if(JTFornecedor.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(null, "Gostaria de alterar o registro?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                Fornecedor f = new Fornecedor();
                FornecedorDAO dao = new FornecedorDAO();
                
                f.setIdFornecedor((int) JTFornecedor.getValueAt(JTFornecedor.getSelectedRow(), 0));
                f.setRazaoSocial(txtRazaoSocial.getText());
                f.setCNPJ(txtCNPJ.getText());
                f.setIE(txtIE.getText());
                f.setEnd(txtRua.getText());
                f.setBairro(txtBairro.getText());
                f.setCidade(txtCidade.getText());
                f.setUF((String) jcbUF.getSelectedItem());
                f.setFoneFixo(txtFoneFixo.getText());
                f.setFoneCelular(txtFoneCelular.getText());
                f.setEmail(txtEmail.getText());
                f.setResp(txtResponsavel.getText());
                
                dao.update(f);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar!");
        }
        limpaCamposForm();
        readTableFornecedores();
    }//GEN-LAST:event_btnAlterarFornActionPerformed
    
    private void JTFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFornecedorFocusLost

    }//GEN-LAST:event_JTFornecedorFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        readTableFornForDesc(txtBuscaForn.getText());
        limpaCamposForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastraFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastraFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTFornecedor;
    private javax.swing.JButton btnAlterarForn;
    private javax.swing.JButton btnCadFornecedor;
    private javax.swing.JButton btnCanFornecedor;
    private javax.swing.JButton btnExcluirForn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbUF;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBuscaForn;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFoneCelular;
    private javax.swing.JFormattedTextField txtFoneFixo;
    private javax.swing.JFormattedTextField txtIE;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
